#!/usr/bin/env python

import sys
import json
import argparse
import os.path
import subprocess
import nbt
import shutil

from lib.playground_config import PlaygroundConfig, load_playground_config

this_dir = os.path.dirname(os.path.realpath(__file__))

USB_STICK_STAGING_DIR = "/tmp/playground-usb-stick-staging"

MAC_LAUNCHER_PROFILE_JSON_PATH = 'Mac/StartMinecraft.app/Contents/MacOS/Library/Application Support/minecraft/launcher_profiles.json'
WINDOWS_LAUNCHER_PROFILE_JSON_PATH = 'Windows/Minecraft/Data/.minecraft/launcher_profiles.json'

MAC_SERVERS_DAT_PATH = 'Mac/StartMinecraft.app/Contents/MacOS/Library/Application Support/minecraft/servers.dat'
WINDOWS_SERVERS_DAT_PATH = 'Windows/Minecraft/Data/.minecraft/servers.dat'

MAC_MINECRAFT_OPTIONS_TXT_PATH = 'Mac/StartMinecraft.app/Contents/MacOS/Library/Application Support/minecraft/options.txt'
WINDOWS_MINECRAFT_OPTIONS_TXT_PATH = 'Windows/Minecraft/Data/.minecraft/options.txt'

MAC_CHROMIUM_EXECUTABLE_SCRIPT_PATH = 'Mac/StartWebBrowser.app/Contents/MacOS/wrapper'
WINDOWS_CHROMIUM_EXECUTABLE_SCRIPT_PATH = 'Windows/StartWebBrowser.bat'

parser = argparse.ArgumentParser()
parser.add_argument('playground_name', type=str, help='help TODO')
subparsers = parser.add_subparsers(help='sub-command help')

def destructive_rsync(src, dest):
    if not os.path.isdir(src):
        raise Exception(src  + " does not exist.")

    if not os.path.isdir(dest):
        raise Exception(dest  + " does not exist.")

    cmd = [
        "/usr/bin/rsync",
        "--size-only",
        "--omit-dir-times",
        "-avz",
        "--delete",
        src + "/",
        dest + "/"
    ]
    if subprocess.call(cmd)!=0:
        raise Exception("FAILED: {}".format(" ".join(cmd)))

def verify_dir_contains_seemingly_valid_image(target_dir):
    if not os.path.isdir(target_dir + "/Mac") or not os.path.isdir(target_dir + "/Windows"):
        raise Exception(target_dir  + " does not appear to contain a valid usb stick image.")

def copy_usb_stick_file(file_name, dest_path):
    shutil.copyfile(os.path.join(this_dir, "usb-stick-files", file_name), dest_path)

def load_launcher_profile_for_player(launcher_profile_json_file, player_name):
    reference_minecraft_profiles = json.loads(open(launcher_profile_json_file).read())
    entry = None
    for player_uuid in reference_minecraft_profiles["authenticationDatabase"]:
        maybe_entry = reference_minecraft_profiles["authenticationDatabase"][player_uuid]
        if maybe_entry["displayName"] == player_name:
            return (player_uuid, maybe_entry, reference_minecraft_profiles["clientToken"])
    raise Exception("no profile found for {} in file {}".format(player_name, launcher_profile_json_file))

def usb_stick_staging_dir(playground_name):
    return os.path.join(USB_STICK_STAGING_DIR, playground_name)

def overwrite_launcher_file(player_key, player_entry, client_token, launcher_profiles_json_file):
    content = json.loads(open(launcher_profiles_json_file).read())
    content["authenticationDatabase"] = {}
    content["authenticationDatabase"][player_key] = player_entry
    content["selectedUser"] = player_key
    content["clientToken"] = client_token
    content_str = json.dumps(content, sort_keys=True, indent=2, separators=(',', ': '))
    print ""
    print "Writing launcher profile json: " + launcher_profiles_json_file
    print content_str
    f = open(launcher_profiles_json_file, 'w')
    f.write(content_str + "\n")
    f.close()

def set_minecraft_server_list(servers_dat_file, server_name, server_ip_port):
    nbtfile = nbt.nbt.NBTFile()
    servers = nbt.nbt.TAG_List(nbt.nbt.TAG_Compound)
    servers.name = "servers"
    nbtfile.tags = [servers]

    server = nbt.nbt.TAG_Compound()
    nbtfile["servers"].tags = [server]

    server.tags = [
        nbt.nbt.TAG_String(name=u'name', value=server_name),
        nbt.nbt.TAG_String(name=u'ip', value=server_ip_port)
    ]

    print ""
    print "Server entries: {}".format(servers_dat_file)
    for server_tag in nbtfile["servers"].tags:
        for tag in server_tag:
            print(server_tag[tag].name + "=" + str(server_tag[tag]))

    f = open(servers_dat_file, "w")
    nbtfile.write_file(buffer=f)
    f.close()

def customize_chromium_launch_file(startup_url, chromium_launch_file):
    launch_file_content = open(chromium_launch_file).read().strip()

    last_word = launch_file_content.split(" ")[-1]
    if last_word.startswith("http"):
        launch_file_content = launch_file_content.replace(" " + last_word, "")

    launch_file_content = launch_file_content + " " + startup_url
    f = open(chromium_launch_file, "w")
    f.write(launch_file_content)
    f.close()

def pull(args):
    playground_config = load_playground_config(args.playground_name, args.playground_config_file)
    staging_dir = usb_stick_staging_dir(args.playground_name)
    verify_dir_contains_seemingly_valid_image(playground_config.usb_stick_dir)
    if not os.path.isdir(staging_dir):
        os.makedirs(staging_dir)
    destructive_rsync(playground_config.usb_stick_dir, staging_dir)

pull_parser = subparsers.add_parser("pull", help='{} pull')
pull_parser.add_argument('playground_config_file', help='json config for playgrounds')
pull_parser.set_defaults(func=pull)

def pristine(args):
    playground_config = load_playground_config(args.playground_name, args.playground_config_file)
    staging_dir = usb_stick_staging_dir(args.playground_name)
    verify_dir_contains_seemingly_valid_image(args.image_dir)
    if not os.path.isdir(staging_dir):
        os.makedirs(staging_dir)
    destructive_rsync(args.image_dir, staging_dir)

pristine_parser = subparsers.add_parser("pristine", help='{} pristine')
pristine_parser.add_argument('playground_config_file', help='json config for playgrounds')
pristine_parser.add_argument('image_dir', help='path to reference usb image.')
pristine_parser.set_defaults(func=pristine)

def customize(args):
    playground_config = load_playground_config(args.playground_name, args.playground_config_file)
    staging_dir = usb_stick_staging_dir(args.playground_name)
    verify_dir_contains_seemingly_valid_image(staging_dir)

    player_key, player_entry, client_token = load_launcher_profile_for_player(
        playground_config.minecraft_reference_launcher_profile_json_file,
        playground_config.initial_minecraft_player_name_for_oogway)
    overwrite_launcher_file(player_key, player_entry, client_token, os.path.join(staging_dir, MAC_LAUNCHER_PROFILE_JSON_PATH))
    overwrite_launcher_file(player_key, player_entry, client_token, os.path.join(staging_dir, WINDOWS_LAUNCHER_PROFILE_JSON_PATH))

    world_server_name_in_servers_dat = args.playground_name + " world server"
    world_server_ip_port = playground_config.fully_qualified_domain_name + ":" + str(playground_config.minecraft_server_port)
    set_minecraft_server_list(os.path.join(staging_dir, MAC_SERVERS_DAT_PATH), world_server_name_in_servers_dat, world_server_ip_port)
    set_minecraft_server_list(os.path.join(staging_dir, WINDOWS_SERVERS_DAT_PATH), world_server_name_in_servers_dat, world_server_ip_port)

    playground_homepage = "http://" + \
        args.playground_name + ":" + playground_config.web_password + "@" + \
        playground_config.fully_qualified_domain_name + "/" + args.playground_name + "/"
    customize_chromium_launch_file(playground_homepage, os.path.join(staging_dir, MAC_CHROMIUM_EXECUTABLE_SCRIPT_PATH))
    customize_chromium_launch_file(playground_homepage, os.path.join(staging_dir, WINDOWS_CHROMIUM_EXECUTABLE_SCRIPT_PATH))

    copy_usb_stick_file('options.txt', os.path.join(staging_dir, MAC_MINECRAFT_OPTIONS_TXT_PATH))
    copy_usb_stick_file('options.txt', os.path.join(staging_dir, WINDOWS_MINECRAFT_OPTIONS_TXT_PATH))

customize_parser = subparsers.add_parser("customize", help='{} customize')
customize_parser.add_argument('playground_config_file', help='json config for playgrounds')
customize_parser.set_defaults(func=customize)

def push(args):
    playground_config = load_playground_config(args.playground_name, args.playground_config_file)
    staging_dir = usb_stick_staging_dir(args.playground_name)
    verify_dir_contains_seemingly_valid_image(staging_dir)
    destructive_rsync(staging_dir, playground_config.usb_stick_dir)

pull_parser = subparsers.add_parser("push", help='{} push')
pull_parser.add_argument('playground_config_file', help='json config for playgrounds')
pull_parser.set_defaults(func=push)

args = parser.parse_args()
args.func(args)
