#!/usr/bin/env python

import argparse
import os.path
import os

from lib import const
from lib.core import ssh_parts, scp_parts, ssh_exec, ssh_exec_all, ssh_get, scp_r, \
    set_current_server_config, load_current_server_config

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(help='sub-command help')

def add_simple_subparser(f):
    command_name = f.__name__.replace("_", "-")
    p = subparsers.add_parser(command_name, help='{} help'.format(command_name))
    p.set_defaults(func=f)

def use(args):
    set_current_server_config(args.server_label, args.server_config_file)

use_parser = subparsers.add_parser('use', help='use help')
use_parser.add_argument('server_label', help='server config to use, from config file')
use_parser.add_argument('server_config_file', help='path to server config file')
use_parser.set_defaults(func=use)

def check(args):
    ssh_exec("uname -a")
add_simple_subparser(check)

def bootstrap(args):
    config = load_current_server_config()

# TODO: make a common set of maps everyone can see
# echo "deb http://packages.mapcrafter.org/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/mapcrafter.list
# sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/ubuntu/keyring.gpg
# sudo apt-get install mapcrafter
# sudo apt-get install imagemagick

    ssh_exec_all([
        "sudo add-apt-repository {} -y".format(config.modern_gradle_apt_repo), # need a modern gradle
        "sudo add-apt-repository {} -y".format(config.modern_nginx_apt_repo), # need a modern nginx
        "echo \"deb http://packages.mapcrafter.org/debian $(lsb_release -sc) main\" | sudo tee /etc/apt/sources.list.d/mapcrafter.list",
        "sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/debian/keyring.gpg",
        "sudo apt-get update",
        "sudo apt-get install apache2-utils build-essential dstat git gradle htop maven nginx nodejs-legacy npm openjdk-7-jdk python-pip python-dev sysstat tmux -y",
        "sudo pip install virtualenv virtualenvwrapper"
    ])
    ssh_exec("file RaspberryJuiceSpongePlugin/.git || git clone {} --recursive".format(config.raspberry_juice_sponge_plugin_git_repo))
    ssh_exec("file ipython/.git || git clone {} --recursive".format(config.ipython_git_repo))
    ssh_exec("file mcpi/.git || git clone {}".format(config.mcpi_git_repo))
    ssh_exec("file mcgamedata/.git || git clone {}".format(config.mcgamedata_git_repo))
    ssh_exec("file oogway/.git || git clone {}".format(config.oogway_git_repo))

    # set up nginx, notably to be able to point to playground nginx.conf's
    scp_r("server-config/nginx.conf", "/tmp")
    ssh_exec_all([
        "sudo cp /tmp/nginx.conf /etc/nginx/nginx.conf",
        "sudo /etc/init.d/nginx reload"
    ])
add_simple_subparser(bootstrap)

def clean_code(args):
    ssh_exec_all([
        "rm -rf ipython",
        "rm -rf mcgamedata",
        "rm -rf mcpi",
        "rm -rf oogway",
        "rm -rf RaspberryJuiceSpongePlugin"
    ])
add_simple_subparser(clean_code)

def clean_ipython(args):
    ssh_exec("rm -rf {}".format(const.PYTHON_VIRTUALENV))
add_simple_subparser(clean_ipython)

def clean_minecraft_server(args):
    ssh_exec("rm -rf {}".format(const.MINECRAFT_LATEST_DIR))
add_simple_subparser(clean_minecraft_server)

def clean_artifacts(args):
    clean_ipython(args)
    clean_minecraft_server(args)
add_simple_subparser(clean_artifacts)

def clean_all(args):
    clean_code(args)
    clean_artifacts(args)
add_simple_subparser(clean_all)

def pull(args):
    config = load_current_server_config()

    ssh_exec_all([
        "cd $HOME/RaspberryJuiceSpongePlugin",
        "git pull --all",
        "git checkout {}".format(config.raspberry_juice_sponge_plugin_git_branch),
        "git submodule update --init --recursive",

        "cd $HOME/ipython",
        "git pull --all",
        "git checkout {}".format(config.ipython_git_branch),
        "git submodule update --init --recursive",

        "cd $HOME/mcpi",
        "git pull --all",
        "git checkout {}".format(config.mcpi_git_branch),

        "cd $HOME/mcgamedata",
        "git pull --all",
        "git checkout {}".format(config.mcgamedata_git_branch),

        "cd $HOME/oogway",
        "git pull --all",
        "git checkout {}".format(config.oogway_git_branch)
    ])
add_simple_subparser(pull)

def build_minecraft_gradle(args):
    ssh_exec_all([
        "cd RaspberryJuiceSpongePlugin/submodules/Sponge",
        "time ./gradlew setupDecompWorkspace --refresh-dependencies",
        "time ./gradlew"
    ])

def populate_minecraft_latest_with_minecraft_server(args):
    sponge_build_dir = "RaspberryJuiceSpongePlugin/submodules/Sponge/build/libs/"
    new_executable_jar = os.path.join(sponge_build_dir, ssh_get("ls {} | egrep '^sponge-' | egrep -v '(javadoc|release|sources)'".format(sponge_build_dir)))

    ssh_exec_all([
        "rm -rf {}".format(const.MINECRAFT_LATEST_DIR),
        "mkdir {}".format(const.MINECRAFT_LATEST_DIR),
        "cp {} {}".format(new_executable_jar, os.path.join(const.MINECRAFT_LATEST_DIR, const.MINECRAFT_SERVER_JAR_NAME)),
        "cd {}".format(const.MINECRAFT_LATEST_DIR),
        "time java -jar {} install".format(const.MINECRAFT_SERVER_JAR_NAME),
        "ls -lh ."
    ])

def build_minecraft_server(args):
    build_minecraft_gradle(args)
    populate_minecraft_latest_with_minecraft_server(args)
add_simple_subparser(build_minecraft_server)

def build_raspberry_juice_plugin_gradle(args):
    ssh_exec_all([
        "cd RaspberryJuiceSpongePlugin",
        "time gradle --no-rebuild :clean :build"
    ])

def populate_minecraft_latest_with_raspberry_juice_plugin(args):
    new_plugin_jar = ssh_get("ls RaspberryJuiceSpongePlugin/build/libs/RaspberryJuiceSpongePlugin*.jar")
    mods_dir = os.path.join(const.MINECRAFT_LATEST_DIR, "mods")
    ssh_exec_all([
        "rm -rf {}".format(mods_dir),
        "mkdir -p {}".format(mods_dir),
        "cp {} {}".format(new_plugin_jar, mods_dir),
        "ls -lh {}".format(mods_dir)
    ])

def build_raspberry_juice_plugin(args):
    build_raspberry_juice_plugin_gradle(args)
    populate_minecraft_latest_with_raspberry_juice_plugin(args)
add_simple_subparser(build_raspberry_juice_plugin)

def build_ipython_3x(args):
    ssh_exec_all([
        "virtualenv --no-site-packages " + const.PYTHON_VIRTUALENV,
        const.PYTHON_VIRTUALENV + "/bin/pip install invoke jinja2 jsonschema pyzmq pygments tornado",
        "npm install less bower",
        "cd ipython",
        "../{}/bin/python setup.py install".format(const.PYTHON_VIRTUALENV)
    ])
add_simple_subparser(build_ipython_3x)

def build(args):
    build_minecraft_server(args)
    build_raspberry_juice_plugin(args)
    build_ipython_3x(args)
add_simple_subparser(build)

def reboot(args):
    ssh_exec("sudo reboot")
add_simple_subparser(reboot)

def ssh(args):
    parts = ssh_parts()
    ssh_bin = parts.pop(0)
    parts.insert(0, "") # dunno why
    os.execv(ssh_bin, parts)
add_simple_subparser(ssh)

def scp(args):
    parts = scp_parts(args.local_path, args.remote_path)
    scp_bin = parts.pop(0)
    parts.insert(0, "") # dunno why
    os.execv(scp_bin, parts)
scp_parser = subparsers.add_parser("scp", help='{} scp')
scp_parser.add_argument('local_path', help='copy from local file or dir')
scp_parser.add_argument('remote_path', help='copy to remote file or dir')
scp_parser.set_defaults(func=scp)


args = parser.parse_args()
args.func(args)
