#!/usr/bin/env python

import argparse
import json
import os.path
import subprocess
import sys

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(help='sub-command help')

def settings_path():
  home = os.path.expanduser("~")
  return os.path.join(home, '.mcfunlab.json')

def load_settings():
  settings_not_found_exception = Exception(
      "Required ec2 settings not found. " +
      "Please run 'server use --help' for information about what must be set up.")

  if os.path.isfile(settings_path()) != True:
    raise settings_not_found_exception

  settings = json.loads(open(settings_path()).read())

  if 'ec2_private_key_file' not in settings or \
    'ec2_user' not in settings or \
    'ec2_host' not in settings:
    raise settings_not_found_exception

  return settings

def ssh(command):
  settings = load_settings()
  user_at_host = "{}@{}".format(settings['ec2_user'], settings['ec2_host'])
  parts = [
    'ssh', '-i', settings['ec2_private_key_file'],
    user_at_host,
    command
  ]
  cmd = " ".join(parts)
  print "> {} {}".format(user_at_host, cmd)
  sys.stderr.write("< {} ".format(user_at_host))
  if subprocess.call(parts)!=0:
    raise Exception("FAILED: {}".format(cmd))

def use(args):
  json_settings_str = json.dumps({
    'ec2_private_key_file': args.ec2_private_key_file,
    'ec2_user': args.ec2_user,
    'ec2_host': args.ec2_host
  }, sort_keys=True, indent=2, separators=(',', ': '))

  f = open(settings_path(), 'w')
  f.write(json_settings_str + "\n")
  f.close()

use_parser = subparsers.add_parser('use', help='use help')
use_parser.add_argument('ec2_private_key_file', help='ec2 private key file')
use_parser.add_argument('ec2_user', help='user to log into the host as')
use_parser.add_argument('ec2_host', help='ec2 target host')
use_parser.set_defaults(func=use)

def check(args):
  ssh("uname -a")

check_parser = subparsers.add_parser('check', help='check help')
check_parser.set_defaults(func=check)


def bootstrap(args):
  ssh("sudo apt-get update")
  ssh("sudo apt-get install build-essential git htop maven openjdk-7-jdk python-pip python-dev tmux -y")
  ssh("file CanaryMod/.git || git clone https://github.com/CanaryModTeam/CanaryMod")
  ssh("file CanaryRaspberryJuice/.git || git clone https://github.com/sconover/CanaryRaspberryJuice")

bootstrap_parser = subparsers.add_parser('bootstrap', help='bootstrap help')
bootstrap_parser.set_defaults(func=bootstrap)

args = parser.parse_args()
args.func(args)
