MINECRAFT_LATEST_DIR="minecraft-latest"
MINECRAFT_SERVER_JAR_NAME = "sponge-minecraft-server.jar"
SPIGOT_LATEST_JAR_LOCATOR_COMMAND = "ls -r ~/spigot-buildtools/spigot-*.jar | head -n 1 | xargs readlink -f"
GRPC_CRAFT_PLUGIN_JAR_LOCATOR_COMMAND = "ls -r ~/grpc-craft/plugin/target/plugin-*.jar | head -n 1 | xargs readlink -f"
PYTHON_VIRTUALENV=".python-virtualenv"
