MINECRAFT_LATEST_DIR="minecraft-latest"
MINECRAFT_SERVER_JAR_NAME = "sponge-minecraft-server.jar"
SPIGOT_LATEST_JAR_LOCATOR_COMMAND = "ls -r ~/spigot-buildtools/spigot-*.jar | head -n 1 | xargs readlink -f"
GRPC_CRAFT_PLUGIN_JAR_LOCATOR_COMMAND = "ls -r ~/grpc-craft/plugin/target/plugin-*.jar | head -n 1 | xargs readlink -f"
GRPC_CRAFT_PYTHON_CLIENT_DIR_LOCATOR_COMMAND = "echo ~/grpc-craft/python/oogway_client | xargs readlink -f"
GRPC_CRAFT_PYTHON_CLIENT_REQUIREMENTS_TXT_LOCATOR_COMMAND = "echo 'grpc-craft/python/oogway_client/requirements.txt'"
PYTHON_VIRTUALENV=".python-virtualenv"

MINECRAFT_SERVER_VARIANT_SPIGOT_GRPC="spigot_grpc"
MINECRAFT_SERVER_VARIANT_SPONGE_MCPI="sponge_mcpi"